# Generated by Django 3.1.7 on 2021-03-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('PM10', models.IntegerField()),
                ('NO2', models.IntegerField()),
                ('SO2', models.IntegerField()),
                ('O3', models.IntegerField()),
                ('AQI', models.IntegerField()),
            ],
            options={
                'db_table': 'AQI_da',
            },
        ),
    ]
