# Generated by Django 3.1.7 on 2021-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210317_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
