# Generated by Django 3.1.7 on 2021-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.DateField(),
        ),
    ]
